plugins {
    id 'java'
    id 'maven-publish'
    id("com.gradleup.shadow") version "9.0.0-beta17"
}

group = 'it.alessandrozap'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        url = "https://oss.sonatype.org/content/repositories/snapshots/"
    }
    maven {
        name = "jitpack"
        url = "https://jitpack.io/"
    }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.20.6-R0.1-SNAPSHOT")
    compileOnly 'org.projectlombok:lombok:1.18.32'

    compileOnly("com.mojang:authlib:6.0.58")
    compileOnly 'com.github.decentsoftware-eu:decentholograms:2.9.2'

    annotationProcessor 'org.projectlombok:lombok:1.18.32'
    shadow 'org.reflections:reflections:0.10.2'
}

test {
    useJUnitPlatform()
}

compileJava.options.encoding = 'UTF-8'

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

task sourcesJar(type: Jar) {
    archiveClassifier.set('sources')
    from sourceSets.main.allSource
}

tasks.named('jar') {
    archiveClassifier.set('unshaded')
}

tasks {
    build {
        dependsOn 'shadowJar'
    }

    shadowJar {
        mergeServiceFiles()
        archiveClassifier.set('')
        configurations = [project.configurations.getByName('shadow')]

        exclude 'org/slf4j/**'
        exclude 'net.minecraft'
        exclude 'assets/**'
        exclude '**/it/unimi/**'

        exclude 'META-INF/maven/**'
        exclude 'META-INF/*.SF'
        exclude 'META-INF/*.DSA'
        exclude 'META-INF/*.RSA'

        relocate 'org.reflections', 'it.alessandrozap.utilsapi.libs.reflections'
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = 'it.alessandrozap.api'
            artifactId = 'UtilsAPI'
            version = '1.0'

            artifact tasks.shadowJar
            artifact sourcesJar
        }
    }
}

tasks.named("publishMavenPublicationToMavenLocal") {
    dependsOn tasks.named("shadowJar")
}